//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PrognozEDWEntities : DbContext
    {
        public PrognozEDWEntities()
            : base("name=PrognozEDWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<User1C> FindUsers1C(string nameRU)
        {
            var nameRUParameter = nameRU != null ?
                new ObjectParameter("nameRU", nameRU) :
                new ObjectParameter("nameRU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<User1C>("FindUsers1C", nameRUParameter);
        }
    
        public virtual ObjectResult<UserCRM> FindUsersCRM(string str)
        {
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserCRM>("FindUsersCRM", strParameter);
        }
    }
}
