//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal3.Models
{
    using System;
    
    public partial class UserSpr
    {
        public int ID { get; set; }
        public string FullNameRu { get; set; }
        public string DomainName { get; set; }
        public string EMailAddress { get; set; }
        public string StaffCode { get; set; }
        public string FirstNameRu { get; set; }
        public string LastNameRu { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
    }
}
